### ISSUE TITLE
Communication issues with updated server code

### ISSUE THREAD

**Issue by brandogw** [FYNCH-BIO/evolver#40]
I find this error when updating the code. Seems like there's still some thing I'm not setting up properly.

I'm currently using Master in both the DPU and Arduino branches.

```
od_135r,1000,_!

Traceback (most recent call last):
  File "/home/pi/evolver/evolver/evolver_server.py", line 246, in run_commands
    returned_data = serial_communication(command['param'], command['value'], command['type'])
  File "/home/pi/evolver/evolver/evolver_server.py", line 284, in serial_communication
    raise EvolverSerialError('Error: Response has incorrect address.\n\tExpected: ' + param + '\n\tFound:' + address)
evolver_server.EvolverSerialError: Error: Response has incorrect address.
	Expected: od_135
	Found:
od_90r,1000,_!
od_90b,32114,31657,31284,31869,31740,31508,
Traceback (most recent call last):
  File "/home/pi/evolver/evolver/evolver_server.py", line 246, in run_commands
    returned_data = serial_communication(command['param'], command['value'], command['type'])
  File "/home/pi/evolver/evolver/evolver_server.py", line 286, in serial_communication
    raise EvolverSerialError('Error: Response did not have valid serial communication termination string!\n\tExpected: ' +  evolver_conf['serial_end_incoming'] + '\n\tFound: ' + response[len(response) - 3:])
evolver_server.EvolverSerialError: Error: Response did not have valid serial communication termination string!
	Expected: end
	Found: 08,
od_ledr,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,2500,_!
od_lede,2500,2500,2500,2500,
Traceback (most recent call last):
  File "/home/pi/evolver/evolver/evolver_server.py", line 246, in run_commands
    returned_data = serial_communication(command['param'], command['value'], command['type'])
  File "/home/pi/evolver/evolver/evolver_server.py", line 286, in serial_communication
    raise EvolverSerialError('Error: Response did not have valid serial communication termination string!\n\tExpected: ' +  evolver_conf['serial_end_incoming'] + '\n\tFound: ' + response[len(response) - 3:])
evolver_server.EvolverSerialError: Error: Response did not have valid serial communication termination string!
	Expected: end
	Found: 00,
stirr,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,_!

Traceback (most recent call last):
  File "/home/pi/evolver/evolver/evolver_server.py", line 246, in run_commands
    returned_data = serial_communication(command['param'], command['value'], command['type'])
  File "/home/pi/evolver/evolver/evolver_server.py", line 284, in serial_communication
    raise EvolverSerialError('Error: Response has incorrect address.\n\tExpected: ' + param + '\n\tFound:' + address)
evolver_server.EvolverSerialError: Error: Response has incorrect address.
	Expected: stir
	Found:
tempr,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,_!
tempb,1967,1948,1938,1935,
Traceback (most recent call last):
  File "/home/pi/evolver/evolver/evolver_server.py", line 246, in run_commands
    returned_data = serial_communication(command['param'], command['value'], command['type'])
  File "/home/pi/evolver/evolver/evolver_server.py", line 286, in serial_communication
    raise EvolverSerialError('Error: Response did not have valid serial communication termination string!\n\tExpected: ' +  evolver_conf['serial_end_incoming'] + '\n\tFound: ' + response[len(response) - 3:])
evolver_server.EvolverSerialError: Error: Response did not have valid serial communication termination string!
	Expected: end
	Found: 35,
Broadcasting data
{'data': {}, 'config': {'lxml': {'fields_expected_incoming': 17, 'fields_expected_outgoing': 17, 'recurring': False, 'value': ['4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095']}, 'od_135': {'fields_expected_incoming': 17, 'fields_expected_outgoing': 2, 'recurring': True, 'value': '1000'}, 'od_90': {'fields_expected_incoming': 17, 'fields_expected_outgoing': 2, 'recurring': True, 'value': '1000'}, 'od_led': {'fields_expected_incoming': 17, 'fields_expected_outgoing': 17, 'recurring': True, 'value': ['2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500', '2500']}, 'pump': {'fields_expected_incoming': 49, 'fields_expected_outgoing': 49, 'recurring': False, 'value': None}, 'stir': {'fields_expected_incoming': 17, 'fields_expected_outgoing': 17, 'recurring': True, 'value': ['15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15']}, 'temp': {'fields_expected_incoming': 17, 'fields_expected_outgoing': 17, 'recurring': True, 'value': ['4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095', '4095']}}}

```

**Comment by brandogw** [comment]
Solved with added delays on Arduino Serial output. 

https://github.com/FYNCH-BIO/evolver-arduino/commit/e202de53139d8b2c620bbf4445656311f34ca967
