### ISSUE TITLE
Fluidic commands not going through 

### ISSUE THREAD

**Issue by brandogw** [FYNCH-BIO/evolver#46]
When trying to send fluidic commands via the GUI. In this case, printed the value variable.

```
Received COMMAND
['13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '13', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
13
Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.6/site-packages/python_socketio-3.0.0-py3.6.egg/socketio/asyncio_server.py:296> exception=TypeError("'NoneType' object does not support item assignment",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/python_socketio-3.0.0-py3.6.egg/socketio/asyncio_server.py", line 297, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.6/site-packages/python_socketio-3.0.0-py3.6.egg/socketio/asyncio_server.py", line 325, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/home/pi/evolver/evolver/evolver_server.py", line 51, in on_command
    evolver_conf['experimental_params'][param]['value'][i] = value[i]
TypeError: 'NoneType' object does not support item assignment
Received COMMAND
```

**Comment by brandogw** [comment]
https://github.com/FYNCH-BIO/evolver/commit/3a5a2a6af9fe21047e91c7295ba9b8624a14cb92
